"""Visual language for the clean-slate HAHA MVP."""

from __future__ import annotations

import streamlit as st


def apply_theme() -> None:
    st.markdown(
        """
        <style>
          :root {--paper:#f6f1e9;--ink:#24201c;--muted:#746b61;--line:#d9cfc0;--red:#a63f34;}
          [data-testid="stHeader"], [data-testid="stToolbar"], [data-testid="stDecoration"], #MainMenu {display:none !important;}
          .block-container {max-width:1440px;padding:20rem 2rem 4rem;}
          [data-testid="stAppViewContainer"] {background:var(--paper);color:var(--ink);}
          [data-testid="stElementContainer"]:has(.header-system),[data-testid="stElementContainer"]:has(.header-system)>[data-testid="stMarkdownContainer"]{display:contents}
          .header-system{position:fixed;z-index:1000;top:0;right:0;left:0;background:#fff;border-bottom:1px solid rgba(217,207,192,.85);box-shadow:none;transition:box-shadow .2s ease}
          .global-header{position:absolute;z-index:3;top:0;right:0;left:0;display:grid;grid-template-columns:auto minmax(max-content,1fr) minmax(20rem,30rem) auto auto;gap:1.15rem;align-items:center;min-height:4.5rem;padding:0 2rem;background:linear-gradient(180deg,rgba(12,35,29,.66),transparent);color:#fff}.header-brand{color:#fff;font:700 1.9rem Georgia,serif;letter-spacing:.04em;text-decoration:none}.global-links,.user-links,.creator-actions{display:flex;align-items:center;white-space:nowrap}.global-links{gap:1.15rem}.user-links{gap:.85rem}.creator-actions{gap:.55rem}.global-links a{color:rgba(255,255,255,.92);font-size:16px;font-weight:500;text-decoration:none}.user-links a,.user-links span{color:rgba(255,255,255,.88);font-size:14px;text-decoration:none}.global-links a.active{color:#fff;font-weight:700}.header-search{display:flex;height:2.65rem;overflow:hidden;border:1px solid rgba(255,255,255,.45);border-radius:9px;background:rgba(255,255,255,.92)}.header-search input{min-width:0;flex:1;border:0;background:transparent;padding:0 .95rem;color:var(--ink);font:400 15px "Microsoft YaHei",sans-serif;outline:0}.header-search button{width:2.8rem;border:0;background:transparent;color:var(--ink);font-size:1.2rem}.script-button,.publish-button{display:grid;min-height:2.65rem;box-sizing:border-box;place-items:center;padding:0 1rem;border-radius:8px;font-size:15px;font-weight:700;text-decoration:none;white-space:nowrap}.script-button{border:1px solid rgba(255,255,255,.65);background:rgba(255,255,255,.9);color:var(--ink)}.publish-button{border:1px solid #ff5d86;background:#ff5d86;color:#fff}.script-button:hover{background:#fff}.publish-button:hover{background:#ff4777}
          .header-visual{position:relative;height:13.5rem;overflow:hidden;color:#fff;background:radial-gradient(circle at 74% 72%,rgba(245,215,115,.5) 0 3%,transparent 3.5%),radial-gradient(ellipse at 72% 110%,#82b654 0 19%,transparent 19.5%),radial-gradient(ellipse at 25% 110%,#47753f 0 31%,transparent 31.5%),linear-gradient(118deg,#174d3d 0%,#1b795b 44%,#77a94f 100%)}.header-visual:before{content:"";position:absolute;inset:38% 0 0;background:repeating-radial-gradient(ellipse at 65% 110%,transparent 0 35px,rgba(209,237,145,.22) 36px 39px,transparent 40px 72px);opacity:.9}.header-visual:after{content:"";position:absolute;right:10%;bottom:-5.5rem;width:17rem;height:17rem;border:2.1rem solid rgba(255,255,255,.08);border-radius:50%}.visual-brand{position:absolute;z-index:2;bottom:2rem;left:3rem;display:flex;flex-direction:column}.visual-brand b{font:800 3.8rem/1 Georgia,serif;letter-spacing:-.08em}.visual-brand span{margin-top:.3rem;font:700 .62rem Arial,sans-serif;letter-spacing:.2em;opacity:.78}.visual-copy{position:absolute;z-index:2;right:4rem;bottom:2.2rem;display:flex;flex-direction:column;align-items:flex-end}.visual-copy strong{font-size:1.05rem}.visual-copy span{margin-top:.35rem;font-size:.68rem;opacity:.8}.visual-seal{position:absolute;z-index:2;top:5.5rem;left:48%;display:grid;width:2.8rem;height:2.8rem;place-items:center;border:2px solid rgba(255,255,255,.55);border-radius:50%;font:700 1.2rem Georgia,serif;transform:rotate(-8deg)}
          .channel-nav{display:grid;grid-template-columns:auto minmax(0,1fr) minmax(17rem,20rem);gap:1rem;padding:.7rem 2rem;background:#fff;border-top:1px solid rgba(217,207,192,.6)}.channel-featured{display:flex;gap:.5rem;padding-right:1rem;border-right:1px solid var(--line)}.channel-featured a,.channel-grid>a,.more-menu summary{display:grid;height:36px;box-sizing:border-box;place-items:center;padding:0 18px;border:1px solid #e2ddd5;border-radius:8px;background:#f2eee8;color:#403a34;font-size:15px;text-decoration:none;white-space:nowrap}.channel-featured a:hover,.channel-grid>a:hover,.more-menu summary:hover{border-color:#ddb3aa;background:#f8e4df;color:var(--red)}.channel-featured a.active,.channel-grid>a.active{border-color:var(--red);background:var(--red);color:#fff;font-weight:700}.channel-grid{display:grid;grid-template-columns:repeat(5,minmax(4.6rem,1fr));gap:.5rem}.channel-utilities{display:grid;grid-template-columns:repeat(3,1fr);gap:.45rem .8rem;padding-left:1rem;border-left:1px solid var(--line)}.channel-utilities a{display:flex;align-items:center;min-height:36px;color:#59616a;font-size:14px;text-decoration:none;white-space:nowrap}.channel-utilities a:hover{color:var(--red)}.more-menu{position:relative}.more-menu summary{cursor:pointer;list-style:none}.more-menu summary::-webkit-details-marker{display:none}.mega-menu{position:absolute;z-index:10;top:2.8rem;right:0;display:grid;width:44rem;grid-template-columns:repeat(4,1fr);gap:1.2rem;padding:1.35rem;border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:0 12px 28px rgba(51,42,31,.14)}.mega-menu section{display:flex;flex-direction:column;gap:.55rem}.mega-menu strong{font-size:.78rem}.mega-menu a,.mega-menu span{min-height:0;padding:0;background:none;color:var(--muted);font-size:.72rem}.mega-menu a:hover{background:none;color:var(--red)}
          .block-container:has(.header-system.is-scrolled){padding-top:8rem}.header-system.is-scrolled{box-shadow:0 5px 16px rgba(51,42,31,.12)}.header-system.is-scrolled .header-visual{height:0;opacity:0}.header-system.is-scrolled .global-header{position:relative;background:#fff;color:var(--ink)}.header-system.is-scrolled .header-brand{color:#1ca7d8}.header-system.is-scrolled .global-links a,.header-system.is-scrolled .user-links a,.header-system.is-scrolled .user-links span{color:var(--muted)}.header-system.is-scrolled .script-button{border-color:var(--line);background:#fff}.header-system.is-scrolled .channel-grid>a:nth-of-type(6),.header-system.is-scrolled .channel-grid>a:nth-of-type(8){display:none}.header-system.is-scrolled .channel-grid{grid-template-columns:repeat(4,minmax(4.6rem,1fr))}.header-system.is-scrolled .channel-nav{padding-top:.5rem;padding-bottom:.5rem}.header-visual,.global-header{transition:height .24s ease,opacity .18s ease,background .2s ease,color .2s ease}.block-container{transition:padding-top .24s ease}
          .channel-filters{margin:.8rem 0 1.5rem;padding:1rem 1.2rem;border:1px solid var(--line);border-radius:12px;background:#fff}.channel-filters div,.filter-row{display:flex;align-items:center;gap:.45rem;flex-wrap:wrap}.channel-filters div+div{margin-top:.65rem}.channel-filters b,.filter-row b{width:3.2rem;color:var(--muted);font-size:.74rem}.channel-filters a,.filter-row a,.filter-row span{padding:.38rem .75rem;border-radius:7px;color:var(--muted);font-size:.73rem;text-decoration:none}.channel-filters a:hover,.filter-row a:hover{color:var(--red)}.channel-filters a.active,.filter-row a.active{background:var(--red);color:#fff}.filter-row{margin:.7rem 0;padding:.85rem 1rem;border:1px solid var(--line);border-radius:10px;background:#fff}.region-first{margin-top:1.4rem}
          [data-testid="stHorizontalBlock"] [data-testid="stButton"] button {min-height:2.45rem;}
          .cover {position:relative;aspect-ratio:16/9;height:auto;border-radius:10px;padding:1rem;display:flex;flex-direction:column;justify-content:space-between;color:#fff;overflow:hidden;transition:filter .2s ease,transform .2s ease;}
          .cover span {font:5rem/1 Georgia,serif;opacity:.88;}.cover small {font:700 .63rem Arial,sans-serif;letter-spacing:.12em;}
          .cover.red {background:radial-gradient(circle at 72% 28%,#e4a78e,transparent 23%),linear-gradient(135deg,#501e1b,#b94738);}.cover.featured-cover{aspect-ratio:auto;height:25rem}
          .cover.green {background:linear-gradient(135deg,#1c463e,#6f9b7c);}.cover.blue {background:linear-gradient(135deg,#1d3e5a,#638aa1);}
          .cover.gold {background:linear-gradient(135deg,#715228,#c69c50);}.cover.purple {background:linear-gradient(135deg,#493259,#a67693);}
          .section-title{display:flex;align-items:baseline;justify-content:space-between;margin:2.2rem 0 .9rem}.section-title h2{margin:0;font:700 1.25rem Georgia,serif}.section-title span,.section-title a{color:var(--muted);font-size:.72rem;text-decoration:none}
          .video-card{min-width:0}.video-card h3{display:-webkit-box;min-height:2.7rem;margin:.65rem 0 .28rem;overflow:hidden;color:var(--ink);font:600 .92rem/1.45 "Microsoft YaHei",sans-serif;-webkit-box-orient:vertical;-webkit-line-clamp:2}.video-card p{margin:0;color:var(--muted);font-size:.72rem}.video-card:hover .cover{filter:brightness(.88);transform:scale(1.015)}.video-overlay{position:absolute;z-index:2;right:.55rem;bottom:.45rem;left:.55rem;display:flex;justify-content:space-between;align-items:center;color:#fff;font:600 .65rem Arial,sans-serif;text-shadow:0 1px 3px #000}.video-overlay b{font-weight:600}.play-mark{position:absolute;z-index:3;top:50%;left:50%;display:grid;width:2.5rem;height:2.5rem;place-items:center;border-radius:50%;background:rgba(255,255,255,.88);color:#263c4a;opacity:0;transform:translate(-50%,-45%);transition:opacity .2s ease,transform .2s ease}.video-card:hover .play-mark{opacity:1;transform:translate(-50%,-50%)}
          .region-card{min-height:8rem;padding:1.2rem;border:1px solid var(--line);border-radius:12px;background:#fff}.region-card span{color:var(--muted);font-size:.68rem}.region-card h3{margin:1.5rem 0 .25rem;font:700 1.25rem Georgia,serif}.region-card p{margin:0;color:var(--muted);font-size:.75rem}.topic-card{min-height:11rem;padding:1.5rem;border-radius:16px;color:#fff}.topic-card span{font:700 .62rem Arial,sans-serif;letter-spacing:.12em;opacity:.78}.topic-card h3{margin:2.8rem 0 .35rem;font:700 1.35rem Georgia,serif}.topic-card p{margin:0;opacity:.8}.topic-card.indigo{background:#234c63}.topic-card.vermilion{background:#944638}.topic-card.earth{background:#82603b}.ai-tool{min-height:10rem;padding:1.35rem;border:1px solid var(--line);border-radius:12px;background:#fff}.ai-tool span{color:#345b72;font:700 .62rem Arial,sans-serif;letter-spacing:.1em}.ai-tool h3{margin:.65rem 0 .4rem}.ai-tool strong{display:block;line-height:1.6}.ai-tool p{color:var(--muted);font-size:.72rem}.site-footer{display:flex;align-items:center;gap:1rem;margin-top:4rem;padding:2rem 0;border-top:1px solid var(--line);color:var(--muted)}.site-footer strong{color:var(--ink);font-family:Georgia,serif}.site-footer small{margin-left:auto}
          .creator-head {margin:1rem 0 1.5rem;padding-bottom:1.3rem;border-bottom:1px solid var(--line);}.creator-head span {color:var(--red);font:700 .7rem Arial,sans-serif;letter-spacing:.14em;}.creator-head h2{margin:.35rem 0;font:700 2rem Georgia,serif;}.creator-head p{margin:0;color:var(--muted);}.upload-tip {margin:0 0 1rem;padding:.7rem .85rem;border-radius:8px;background:#eee5d7;color:var(--muted);font-size:.8rem;}
          .creator-rule {display:grid;grid-template-columns:2rem 1fr;column-gap:.55rem;padding:1rem 0;border-bottom:1px solid var(--line);}.creator-rule b{grid-row:span 2;color:var(--red);font:700 1.1rem Georgia,serif;}.creator-rule strong{font-size:.88rem;}.creator-rule span{margin-top:.3rem;color:var(--muted);font-size:.76rem;line-height:1.6;}
          [data-testid="stFileUploaderDropzone"] {min-height:11rem;border:2px dashed #bd897d;background:#fffaf4;}
          .creator-sidebar {display:flex;flex-direction:column;gap:1rem;min-height:24rem;padding:1.2rem 0;border-right:1px solid var(--line);color:var(--muted)}.creator-sidebar strong{color:var(--ink)}.creator-logo{margin-bottom:1rem;color:var(--red);font:700 1.45rem Georgia,serif}.creator-logo span{display:block;color:var(--muted);font:600 .68rem Arial,sans-serif;letter-spacing:.1em}.workspace-top{display:flex;justify-content:space-between;align-items:center;padding:.6rem 0 1rem;border-bottom:1px solid var(--line)}.workspace-top span{color:var(--muted);font-size:.78rem}
          .block-container:has(.creator-sidebar){padding-top:2rem}.studio-v2-head{margin-top:1.2rem}.studio-column-title{margin-bottom:.8rem;padding-bottom:.65rem;border-bottom:1px solid var(--line);color:var(--red);font-size:.78rem;font-weight:800;letter-spacing:.04em}.studio-empty{display:flex;min-height:25rem;align-items:center;justify-content:center;flex-direction:column;gap:.65rem;padding:2rem;border:1px dashed var(--line);border-radius:14px;background:rgba(255,255,255,.48);text-align:center}.studio-empty span{max-width:24rem;color:var(--muted);font-size:.78rem;line-height:1.7}.judgment-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem;margin-bottom:1rem}.judgment-grid div{min-height:4.6rem;padding:.85rem;border:1px solid var(--line);border-radius:10px;background:#fff}.judgment-grid span{display:block;margin-bottom:.35rem;color:var(--muted);font-size:.68rem}.judgment-grid b{font-size:.78rem;line-height:1.55}.zone-note{margin:1rem 0;padding:.85rem;border-left:3px solid var(--red);background:#fff8f1;color:var(--muted);font-size:.72rem;line-height:1.75}.zone-note b{color:var(--ink)}.rewrite-chips{display:flex;flex-wrap:wrap;gap:.45rem;margin:.6rem 0 1rem}.rewrite-chips button{padding:.42rem .7rem;border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--muted);font-size:.7rem}.source-item{margin-bottom:.45rem;padding:.65rem;border:1px solid var(--line);border-radius:8px;background:#fff;color:#3f6174;font-size:.7rem}.audit-item{display:flex;gap:.55rem;margin-bottom:.45rem;padding:.65rem;border-radius:8px;font-size:.7rem;line-height:1.5}.audit-item b{flex:0 0 auto}.audit-item.pass{background:#eaf5ed;color:#356145}.audit-item.check{background:#fff4dc;color:#825f1e}.audit-item.risk,.audit-item.error{background:#fbe8e5;color:#8e3d35}.operation-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.45rem}.operation-grid span{display:flex;justify-content:space-between;padding:.6rem;border-bottom:1px solid var(--line);color:var(--muted);font-size:.68rem}.operation-grid b{color:var(--ink)}.review-empty{padding:1rem;border:1px dashed var(--line);border-radius:10px;color:var(--muted);font-size:.75rem;line-height:2}
          section,.section-title{scroll-margin-top:9rem}
          @media (max-width:1280px){.global-header{grid-template-columns:auto minmax(18rem,1fr) minmax(18rem,24rem) auto}.user-links{display:none}.channel-nav{grid-template-columns:auto minmax(0,1fr)}.channel-utilities{display:none}.channel-grid{grid-template-columns:repeat(5,minmax(4.5rem,1fr))}}
          @media (max-width:1024px){.block-container{padding-top:18rem}.block-container:has(.header-system.is-scrolled){padding-top:7rem}.global-header{grid-template-columns:auto 1fr auto}.global-links,.user-links{display:none}.header-search{grid-column:2}.creator-actions .script-button{display:none}.channel-nav{grid-template-columns:7rem 1fr}.channel-grid{grid-template-columns:repeat(5,minmax(4rem,1fr))}.mega-menu{right:-4rem;width:34rem}}
          @media (max-width:700px) {.block-container{padding:15rem 1rem 4rem}.global-header{grid-template-columns:auto 1fr auto;gap:.6rem;padding:0 1rem}.header-search{min-width:0}.header-search input{font-size:.7rem}.publish-button{padding:0 .7rem}.header-visual{height:10rem}.visual-copy{display:none}.channel-nav{grid-template-columns:1fr;padding-right:1rem;padding-left:1rem}.channel-featured{display:none}.channel-grid{grid-template-columns:repeat(4,minmax(3.7rem,1fr))}.channel-grid>a:nth-of-type(n+9){display:none}.cover.featured-cover{height:18rem}.creator-sidebar{min-height:0;border-right:0;border-bottom:1px solid var(--line)}.site-footer{align-items:flex-start;flex-direction:column}.site-footer small{margin-left:0}.mega-menu{position:fixed;right:1rem;left:1rem;width:auto}}
        </style>
        """,
        unsafe_allow_html=True,
    )
