"""Visual language for the clean-slate HAHA MVP."""

from __future__ import annotations

import streamlit as st


def apply_theme() -> None:
    st.markdown(
        """
        <style>
          :root {--paper:#f6f1e9;--ink:#24201c;--muted:#746b61;--line:#d9cfc0;--red:#a63f34;}
          [data-testid="stHeader"], [data-testid="stToolbar"], [data-testid="stDecoration"], #MainMenu {display:none !important;}
          .block-container {max-width:1440px;padding:1.2rem 2rem 4rem;}
          [data-testid="stAppViewContainer"] {background:var(--paper);color:var(--ink);}
          .global-nav {display:flex;align-items:center;gap:1rem;white-space:nowrap}.global-nav a{color:var(--muted);font-size:.76rem;text-decoration:none}.global-nav a.active{color:var(--ink);font-weight:700}.global-nav .brand{margin-right:.25rem;color:var(--ink);font:700 1.5rem Georgia,serif;letter-spacing:.04em}
          .header-tools{display:flex;justify-content:space-between;gap:.55rem;color:var(--muted);font-size:.68rem;white-space:nowrap}.header-tools a{color:var(--muted);text-decoration:none}
          [data-testid="stHorizontalBlock"] [data-testid="stButton"] button {min-height:2.45rem;}
          .brand-banner {position:relative;min-height:12rem;margin:1rem 0 0;padding:2.4rem 3rem;overflow:hidden;border-radius:16px;color:#fff;background:radial-gradient(circle at 78% 20%,rgba(228,205,127,.5),transparent 20%),linear-gradient(120deg,#173f3b,#477565 55%,#bb8651)}.brand-banner:after{content:"";position:absolute;right:7%;bottom:-55%;width:18rem;height:18rem;border:2rem solid rgba(255,255,255,.08);border-radius:50%}.brand-banner span{font:700 .65rem Arial,sans-serif;letter-spacing:.16em;opacity:.8}.brand-banner h1{max-width:36rem;margin:.65rem 0;font:700 2.25rem/1.2 Georgia,serif}.brand-banner p{margin:0;opacity:.78}.brand-banner b{position:absolute;right:12%;top:20%;font:700 6rem/1 Georgia,serif;opacity:.13}
          .cover {position:relative;aspect-ratio:16/9;height:auto;border-radius:10px;padding:1rem;display:flex;flex-direction:column;justify-content:space-between;color:#fff;overflow:hidden;transition:filter .2s ease,transform .2s ease;}
          .cover span {font:5rem/1 Georgia,serif;opacity:.88;}.cover small {font:700 .63rem Arial,sans-serif;letter-spacing:.12em;}
          .cover.red {background:radial-gradient(circle at 72% 28%,#e4a78e,transparent 23%),linear-gradient(135deg,#501e1b,#b94738);}.cover.featured-cover{aspect-ratio:auto;height:25rem}
          .cover.green {background:linear-gradient(135deg,#1c463e,#6f9b7c);}.cover.blue {background:linear-gradient(135deg,#1d3e5a,#638aa1);}
          .cover.gold {background:linear-gradient(135deg,#715228,#c69c50);}.cover.purple {background:linear-gradient(135deg,#493259,#a67693);}
          .section-title{display:flex;align-items:baseline;justify-content:space-between;margin:2.2rem 0 .9rem}.section-title h2{margin:0;font:700 1.25rem Georgia,serif}.section-title span,.section-title a{color:var(--muted);font-size:.72rem;text-decoration:none}
          .video-card{min-width:0}.video-card h3{display:-webkit-box;min-height:2.7rem;margin:.65rem 0 .28rem;overflow:hidden;color:var(--ink);font:600 .92rem/1.45 "Microsoft YaHei",sans-serif;-webkit-box-orient:vertical;-webkit-line-clamp:2}.video-card p{margin:0;color:var(--muted);font-size:.72rem}.video-card:hover .cover{filter:brightness(.88);transform:scale(1.015)}.video-overlay{position:absolute;z-index:2;right:.55rem;bottom:.45rem;left:.55rem;display:flex;justify-content:space-between;align-items:center;color:#fff;font:600 .65rem Arial,sans-serif;text-shadow:0 1px 3px #000}.video-overlay b{font-weight:600}.play-mark{position:absolute;z-index:3;top:50%;left:50%;display:grid;width:2.5rem;height:2.5rem;place-items:center;border-radius:50%;background:rgba(255,255,255,.88);color:#263c4a;opacity:0;transform:translate(-50%,-45%);transition:opacity .2s ease,transform .2s ease}.video-card:hover .play-mark{opacity:1;transform:translate(-50%,-50%)}
          .region-card{min-height:8rem;padding:1.2rem;border:1px solid var(--line);border-radius:12px;background:#fff}.region-card span{color:var(--muted);font-size:.68rem}.region-card h3{margin:1.5rem 0 .25rem;font:700 1.25rem Georgia,serif}.region-card p{margin:0;color:var(--muted);font-size:.75rem}.topic-card{min-height:11rem;padding:1.5rem;border-radius:16px;color:#fff}.topic-card span{font:700 .62rem Arial,sans-serif;letter-spacing:.12em;opacity:.78}.topic-card h3{margin:2.8rem 0 .35rem;font:700 1.35rem Georgia,serif}.topic-card p{margin:0;opacity:.8}.topic-card.indigo{background:#234c63}.topic-card.vermilion{background:#944638}.topic-card.earth{background:#82603b}.ai-tool{min-height:10rem;padding:1.35rem;border:1px solid var(--line);border-radius:12px;background:#fff}.ai-tool span{color:#345b72;font:700 .62rem Arial,sans-serif;letter-spacing:.1em}.ai-tool h3{margin:.65rem 0 .4rem}.ai-tool strong{display:block;line-height:1.6}.ai-tool p{color:var(--muted);font-size:.72rem}.site-footer{display:flex;align-items:center;gap:1rem;margin-top:4rem;padding:2rem 0;border-top:1px solid var(--line);color:var(--muted)}.site-footer strong{color:var(--ink);font-family:Georgia,serif}.site-footer small{margin-left:auto}
          .creator-head {margin:1rem 0 1.5rem;padding-bottom:1.3rem;border-bottom:1px solid var(--line);}.creator-head span {color:var(--red);font:700 .7rem Arial,sans-serif;letter-spacing:.14em;}.creator-head h2{margin:.35rem 0;font:700 2rem Georgia,serif;}.creator-head p{margin:0;color:var(--muted);}.upload-tip {margin:0 0 1rem;padding:.7rem .85rem;border-radius:8px;background:#eee5d7;color:var(--muted);font-size:.8rem;}
          .creator-rule {display:grid;grid-template-columns:2rem 1fr;column-gap:.55rem;padding:1rem 0;border-bottom:1px solid var(--line);}.creator-rule b{grid-row:span 2;color:var(--red);font:700 1.1rem Georgia,serif;}.creator-rule strong{font-size:.88rem;}.creator-rule span{margin-top:.3rem;color:var(--muted);font-size:.76rem;line-height:1.6;}
          [data-testid="stFileUploaderDropzone"] {min-height:11rem;border:2px dashed #bd897d;background:#fffaf4;}
          .category-hub {display:grid;grid-template-columns:5rem 5rem minmax(0,1fr) 14rem;gap:1rem;align-items:center;margin:.6rem 0 1.4rem;padding:1rem 0;border-bottom:1px solid var(--line);}.category-feature{display:flex;flex-direction:column;align-items:center;gap:.35rem;color:var(--ink);font-size:.78rem;text-decoration:none}.category-feature i{display:grid;place-items:center;width:2.8rem;height:2.8rem;border-radius:50%;background:#c8614f;color:#fff;font-style:normal;font-size:1.25rem}.category-feature.hot i{background:#d59c45}.category-feature.active strong{color:var(--red)}.category-chips{display:grid;grid-template-columns:repeat(4,minmax(4rem,1fr));gap:.55rem}.category-chips a{padding:.48rem .6rem;border:1px solid #e2d8ca;border-radius:7px;background:#eee8df;color:var(--ink);text-align:center;text-decoration:none;font-size:.78rem}.category-chips a:hover,.category-chips a.active{border-color:#c8614f;background:#fff5ef;color:var(--red)}.category-links{display:grid;grid-template-columns:1fr 1fr;gap:.7rem;color:var(--muted);font-size:.76rem}.category-links span{white-space:nowrap}
          .creator-sidebar {display:flex;flex-direction:column;gap:1rem;min-height:24rem;padding:1.2rem 0;border-right:1px solid var(--line);color:var(--muted)}.creator-sidebar strong{color:var(--ink)}.creator-logo{margin-bottom:1rem;color:var(--red);font:700 1.45rem Georgia,serif}.creator-logo span{display:block;color:var(--muted);font:600 .68rem Arial,sans-serif;letter-spacing:.1em}.workspace-top{display:flex;justify-content:space-between;align-items:center;padding:.6rem 0 1rem;border-bottom:1px solid var(--line)}.workspace-top span{color:var(--muted);font-size:.78rem}
          @media (max-width:1024px){.category-hub{grid-template-columns:4rem 4rem 1fr}.category-links{display:none}.category-chips{grid-template-columns:repeat(3,1fr)}}
          @media (max-width:700px) {.block-container{padding-right:1rem;padding-left:1rem}.global-nav{gap:.65rem;overflow-x:auto}.global-nav .brand{font-size:1.2rem}.brand-banner{min-height:10rem;padding:2rem 1.3rem}.brand-banner h1{font-size:1.65rem}.cover.featured-cover{height:18rem}.category-chips{grid-template-columns:repeat(2,1fr)}.creator-sidebar{min-height:0;border-right:0;border-bottom:1px solid var(--line)}.site-footer{align-items:flex-start;flex-direction:column}.site-footer small{margin-left:0}}
        </style>
        """,
        unsafe_allow_html=True,
    )
